### ISSUE TITLE
mssql+aioodbc sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.aioodbc

### ISSUE THREAD

**Issue by biyani701** [aio-libs/aioodbc#459]
While trying to create DB driver with sqlalchemy, i am getting below error

sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.aioodbc

I am running on windows 11 and python 3.9.10
aioodbc version 0.5.0

Please suggest how to fix this error

**Comment by biyani701** [comment]
SQLAlchemy Version is 2.0.19

**Comment by gordthompson** [comment]
```
pip install aioodbc
```

**Comment by biyani701** [comment]
The issue was resolved after i upgraded sqlalchemy to latest version (2.0.31). is there any minimum required version for aioodbc?

**Comment by gordthompson** [comment]
> is there any minimum required version for aioodbc?

2.0.23

**Comment by danrayson** [comment]
I have:
```
Name: SQLAlchemy
Version: 2.0.36
```
and
```
Name: aioodbc
Version: 0.5.0
```

It's still not working.  Same error.
`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mssql.aiosqlite`

**Comment by danrayson** [comment]
I had a similar error.  Turned out my dialectic was wrong.  I was using `aiosqlite` when it should have been `aioodbc` (obviously).

Now my connection string looks more like: `DATABASE_URL=mssql+aioodbc:`
